coupons/urls.py
from django.urls import include, path
from django.contrib import admin
from ffcu.views import vendor
from coupons import views

# from .views import interview, interviewee, interviewer
from .views import *


urlpatterns = [
    # path('viddi_manager/', admin.site.urls),
    path('home/', vendor.home, name='home'),

    path('vendor/', include(([
        path('', views.manage_dashboard, name='dashboard'),

        path('vendors/', views.UserManagementListView.as_view(),
              name='user_management_list'),
        path('vendors/add/', views.InterviewerSignUpView.as_view(),
              name='user_management_add'),
        path('vendors/<int:pk>/', views.InterviewerUpdateView.as_view(),
              name='user_management_edit'),
        path('vendors/<int:pk>/delete/', views.InterviewerDeleteView.as_view(),
              name='user_management_delete'),

    ], 'vendor'), namespace='vendor')),
]

ffcu/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from ffcu.views import vendor, messages
from coupons.forms import AdminAuthenticationForm, PasswordChangeForm
# from django.contrib.messages import constants as messages
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as coreViews
from django.urls import reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
# from .views import vendor
from coupons import views

urlpatterns = [
    path('home/', vendor.home, name='home'),
    # path('', vendor.home, name="index"),

    path('', vendor.index, name="index"),
    path('user/', vendor.UserLoginView.as_view(), name='user_login'),
    path('password_reset/', vendor.CaptchaPasswordResetView.as_view(), name='password_reset'),
    path('admin/', vendor.AdminLoginView.as_view(), name='login'),

    path('logout/', coreViews.LogoutView.as_view(), name='logout'),
    path('', include('coupons.urls')),

# ]
] + [
    path('password_change/', coreViews.PasswordChangeView.as_view(
        success_url=reverse_lazy('login'),
        form_class=PasswordChangeForm),
        name='password_change'),
    path('password_change/done/', coreViews.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # # Work pending : Forgot Password flow
    # path('password_reset/', interview.CaptchaPasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
    #      name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# #
#


handler404 = messages.error_404
handler500 = messages.error_500

templates/admin_base.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Vendor</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}?key=2" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}?key=2" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}?key=2" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}?key=2" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}?key=2" type="text/css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" crossorigin="anonymous" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" type="text/css" />

  </head>
  <body>
    {% block content %}

    {% endblock %}
     <div class="container-fluid">
        <footer>
        </footer>
        <script src="{% static 'js/waves.js' %}"></script>
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/js.cookie.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
        <script src="{% static 'js/admin.js' %}"></script>
        <script src="{% static 'js/jquery-ui.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
        <script src="{% static 'js/orgval.js' %}"></script>
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" crossorigin="anonymous">
        <script>
           $(document).ready(function() {
               $('table').addClass('table-hover').DataTable({
               	"pagingType": "simple_numbers",
           		language: {
           paginate: {
             next: '<i class="fa fa-angle-right" aria-hidden="true"></i>',
             previous: '<i class="fa fa-angle-left" aria-hidden="true"></i>',
           }
           },
           		"bInfo" : false,
               	columnDefs: [{
           			orderable: false, targets: -1
           		}],
				 "fnDrawCallback": function(oSettings) {
        if (oSettings._iDisplayLength > oSettings.fnRecordsDisplay()) {
            $(oSettings.nTableWrapper).find('.dataTables_paginate').hide();
        }
    }
               });
           });

        </script>
        <script data-jsd-embedded data-key="b40a961e-505b-4aa3-b938-e6931ac84c6f" data-base-url="https://jsd-widget.atlassian.com" src="https://jsd-widget.atlassian.com/assets/embed.js"></script>
     </div>
  </body>
</html>

templates/authbase.html
{% extends "admin_base.html" %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<aside id="leftsidebar" class="sidebar">
   <!-- <div class="Logo_Sidebar">
      {% if user.user_type > 4 %}
      <a><img src="{{ company.img.url }}" style="max-width: 100px;"></a>
      {% elif user.user_type < 2  %}
      <a><img src="{% static 'img/6d792b0b-d307-11e9-956c-42010a8a0ff2' %}" alt="" class="O-Click menu-open"></a>
      <a><img src="{% static 'img/0.png' %}" alt="" class="Second_Image_O menu-open"></a>
      <div class="Arrow A-Open"><span class="Arrow_Manage"></span></div>
      {% endif %}
   </div> -->
   <div class="Logo_Sidebar">
      <a><img src="{% static 'img/FFCU-LOGO_WHITE_PNG.png' %}" alt="" class="O-Click menu-open"></a>
      <a><img src="{% static 'img/0.png' %}" alt="" class="Second_Image_O menu-open"></a>
      <div class="Arrow A-Open"><span class="Arrow_Manage"></span></div>
   </div>
   <div class="toggle_bar">
      <i class="fa fa-bars" aria-hidden="true"></i>
   </div>
   <!-- Menu -->
   <div class="menu">
      <ul class="list menu-open">
        {% if user.user_type < 3 %}
         <li class="active">
            <a href="{% url 'vendor:user_management_list' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/bccbc5c9-cf13-11e9-aa34-42010a8a0fed' %} ">
                  </div>
                  <b>Users</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 10 %}
         <li class="">
            <a href="{% url 'vendor:user_management_list' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/583076b2-cf13-11e9-aa34-42010a8a0fed' %}" class="Das">
                  </div>
                  <b>Vendor</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 10 %}
         <li class="">
            <a href="#">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/c25f6256-cf13-11e9-aa34-42010a8a0fed' %} " class="Das">
                  </div>
                  <b>Coupons</b>
               </span>
            </a>
         </li>
         {% endif %}

      </ul>
   </div>
</aside>
<div class="container-fluid">
</div>


{% block vendorcontent %}

{% endblock %}
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endblock %}

templates/home.html
<h1> HOME PAGE</h1>

templates/index.html
<h1> INDEX PAGE</h1>

templates/login.html
<!-- {% extends "admin_base.html" %} -->
{% load static %}
{% block content %}
  <section class="login d-flex justify-content-center align-items-center">
     <div class="loginFormContainer">
        <div class="Logo Jaro">
           <a href="{% url 'login' %}"><img src="{% static 'img/fc1a6d75-d39c-11e9-8423-42010a8a0ff4' %}"></a>
        </div>
        <div class="Login_Desciption">
           <h4>Welcome <span>back!</span></h4>
        </div>
        <div class="formFields">
           <form method="post" novalidate>
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}">
                  <div class="border_none">

                    <div class="form-group ca">
                       <img src="{% static 'img/2e95ce38-c98a-11e9-86f0-42010a8a0feb' %}" class="icon">
                       {{ form.username }}
                    </div>
                    <div class="form-group ca">
                       <img src="{% static 'img/24d3f0cb-c98a-11e9-86f0-42010a8a0feb' %}" class="icon lock">
                       {{ form.password }}
                    </div>
                    {% for error in form.non_field_errors %}
                    <p style="color:red;">{{ error }}</p>
                    {% endfor %}

                    <div class="Login_Sub">
                       <button class="btn bg-theme" type="submit" id="btnLogin" value="Login" name="login">Login</button  >
                    </div>

                    <div class="Forget_Sub">
                     <a class="float-left" href="{% url 'password_reset' %}">Forgot password?</a>
                    </div>
                  </div>
           </form>
        </div>
     </div>
  </section>
{% endblock %}

templates/user_base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Vendor | User</title>
      <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
      <link rel="stylesheet" href="{% static 'css/all.min.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/style.min.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/custom_user.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/users_responsive.css' %}" type="text/css">
      <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" crossorigin="anonymous" type="text/css">
  </head>
  <body>
    {% block content %}

    {% endblock %}
     <div class="container-fluid">
       {% block extra_js %}

       {% endblock %}
        <footer>
        </footer>

        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/custom_user.js' %}"></script>
        <script src="{% static 'js/responsive_js.js' %}"></script>
        {% block extra_css %}

        {% endblock %}
  </body>
</html>

templates/userbase.html
{% extends "user_base.html" %}
{% load staticfiles %}
{% block content %}
  {% if user.is_authenticated %}
    <header>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <nav class="navbar navbar-expand-lg navbar-light fixed-top">
              <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
              <span class=""><i class="fas fa-bars"></i></span>
              </button> <a class="navbar-brand" href="{% url 'interviewee:dashboard' %}">
                  <img src="https://www.viddi.com.au/static/img/6d792b0b-d307-11e9-956c-42010a8a0ff2" width="100px" >
              </a>
              <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ml-md-auto">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'interviewee:dashboard' %}" id="navbarDropdownMenuLink" data-toggle="dropdown">{{ user.first_name }}</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'logout' %}">logout</a>
                    </div>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    
    {% block intervieweecontent %}

    {% endblock %}
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endblock %}